server:
  port: 8080

eureka:
  instance:
    instance-id: gateway-instance
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  jwt:
    key: test_key_just_local

  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: subject-service
          uri: lb://SUBJECT-SERVICE
          predicates:
            - Path=/api/v1/subjects/**
          filters:
            - MemberAuthorizationFilter

        - id: exec-service
          uri: lb://EXEC-SERVICE
          predicates:
            - Path=/api/v1/exec/**
          filters:
            - MemberAuthorizationFilter

        - id: team-service
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/api/v1/teams/**
          filters:
            - MemberAuthorizationFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**