server:
  port: 8080

eureka:
  instance:
    instance-id: gateway-instance
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: subject-service
          uri: lb://SUBJECT-SERVICE
          predicates:
            - Path=/api/v1/subjects/**
        - id: exec-service
          uri: lb://EXEC-SERVICE
          predicates:
            - Path=/api/v1/exec/**
