server:
  port: 8080

eureka:
  instance:
    instance-id: gateway-instance
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  jwt:
    key: test_key_just_local

  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3002"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - access-control-allow-origin
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
              - teamToken
              - strict-origin-when-cross-origin
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
              - HEAD
      routes:
        - id: subject-service
          uri: lb://SUBJECT-SERVICE
          predicates:
            - Path=/api/v1/subjects/ms/**
          filters:
            - MemberAuthorizationFilter
        - id: subject-service
          uri: lb://SUBJECT-SERVICE
          predicates:
            - Path=/api/v1/subjects/ss/**
          filters:
            - StudentAuthorizationFilter
        - id: subject-service
          uri: lb://SUBJECT-SERVICE
          predicates:
            - Path=/api/v1/subjects/ps/**
          filters:
            - ProAuthorizationFilter

        - id: team-service
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/api/v1/teams/ms/**
          filters:
            - MemberAuthorizationFilter
        - id: team-service
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/api/v1/teams/ss/**
          filters:
            - StudentAuthorizationFilter
        - id: team-service
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/api/v1/teams/ps/**
          filters:
            - ProAuthorizationFilter

        - id: exec-service
          uri: lb://EXEC-SERVICE
          predicates:
            - Path=/api/v1/exec/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**